# BROADCASTING

In [1]:
import numpy as np

In [3]:
arr1= np.arange(3).reshape(1,3)
arr2=np.arange(12).reshape(4,3)
print(arr1+arr2)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


# some more functions of numpy

In [7]:
np.random.random()

0.6064998642068273

In [17]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [19]:
np.random.uniform(3,10)

8.042271454095108

In [23]:
np.random.uniform(1,100,10).reshape(2,5)

array([[21.24077272, 87.9336262 ,  3.71137173, 67.37628351, 42.31317543],
       [56.31029302, 14.89830692, 20.61204742, 80.2737123 , 96.857896  ]])

In [27]:
np.random.randint(1,10)

7

In [29]:
np.random.randint(1,10,5)

array([2, 1, 2, 9, 9])

In [41]:
a= np.random.randint(1,10,6)
print(a)

[8 5 6 4 7 9]


In [43]:
np.max(a)

9

In [55]:
#it gives the index of minimum 
number=np.argmax(a)

In [51]:
np.argmin(a)

3

In [63]:
arrs=np.random.randint(1,10,6)
arrs

array([1, 3, 8, 8, 8, 4])

In [67]:
arrs[arrs%2==1]=-1
arrs

array([-1, -1,  8,  8,  8,  4])

In [71]:
#if we use where function it does not directly change the main array it makes a m=copoy out of it and
#and the it changes that array
arr1=np.random.randint(1,10,6)
arr1

array([4, 1, 9, 7, 5, 6])

In [79]:
out = np.where(arr1%2==1,-1,a)
out

array([ 8, -1, -1, -1, -1,  9])

In [75]:
out

array([ 8, -1, -1, -1, -1,  9])

In [77]:
np.sort(arr1)

array([1, 4, 5, 6, 7, 9])

array([ 7,  3, 13, 28, 22, 12])