# create numpy//n-d arrays


In [2]:
import numpy as np
arr1 = np.array([3,4,5,3,2,4])
print(arr1)

[3 4 5 3 2 4]


In [3]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[3,4,5,3,2,4],[3,4,5,3,2,4]])
print(arr2)

[[3 4 5 3 2 4]
 [3 4 5 3 2 4]]


In [9]:
arr4=np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5=np.identity(6)
print(arr5)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [13]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arr=np.arange(9,67)
arr

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66])

In [15]:
arr=np.arange(9,67,10)
arr

array([ 9, 19, 29, 39, 49, 59])

In [18]:
arr7 = np.linspace(10,20,10)
print(arr7)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [1]:
arr8=arr7.copy()
print(arr8)

NameError: name 'arr7' is not defined