# Numpy operations

In [1]:
import numpy as np 

In [3]:
arr1=np.array([2,4,5,6,4,3])
arr2=np.array([2,4,5,6,4,9])

In [5]:
arr1*arr2

array([ 4, 16, 25, 36, 16, 27])

In [7]:
arr1*3

array([ 6, 12, 15, 18, 12,  9])

In [9]:
arr1-arr2

array([ 0,  0,  0,  0,  0, -6])

In [11]:
arr2>9

array([False, False, False, False, False, False])

In [13]:
 arr3=np.arange(6).reshape(2,3)
 arr4=np.arange(6,12).reshape(3,2)

In [15]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [28]:
print(arr3.max())

5


In [30]:
print(arr3.min())

0


In [34]:
#to know column wise maximum
arr4.min(axis=0)

array([6, 7])

In [36]:
#to know row wise maximum
arr4.min(axis=1)

array([ 6,  8, 10])

In [38]:
#column sum
arr4.sum(axis=0)

array([24, 27])

In [40]:
#row sum
arr4.sum(axis=1)

array([13, 17, 21])

In [42]:
arr4.mean()


8.5

In [44]:
arr4.std()

1.707825127659933

In [46]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [48]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

# Reshaping Numpy arrays


In [51]:
#convert to one dimension
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [53]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [57]:
arr5=np.arange(12,18).reshape(2,3)

In [59]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [61]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [63]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

# Fancy indexing

In [66]:
arr8=np.arange(24).reshape(6,4)

In [68]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

# indexing using boolean arrays

In [89]:
arr34=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr34

array([[85, 16, 27, 29, 46],
       [74, 64, 83, 59, 29],
       [92, 80, 49, 15, 71],
       [30, 82,  6, 60, 26]])

In [91]:
#inddexing using boolean array

In [95]:
arr34[arr34>50]

array([85, 74, 64, 83, 59, 92, 80, 71, 82, 60])

In [ ]:
arr[(arr34>50) & (arr34%2!=0)]