# Indexing slicing and iteration

In [9]:
import numpy as np
#using reshape function

arr1=np.arange(24).reshape(6,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [11]:
arr1[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
arr1[-1]

array([20, 21, 22, 23])

In [15]:
#to get all the rows and a particular column
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [19]:
#iteration
arr1



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
